//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CGWork.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CGWorkTYPE                  129
#define IDD_LIGHTS_DLG                  134
#define IDD_MATERIAL_DLG                136
#define IDD_MOUSESENSETIVITY_DLG        141
#define IDD_DIALOG1                     143
#define IDD_PERSPECTIVEPARS_DLG         143
#define IDD_FINENESSCONTROL_DLG         147
#define IDD_ADVANCED_DLG                153
#define IDD_FILE_RENDERING              157
#define IDD_SUPER_SAMPLING              159
#define IDD_MOTION_BLUR_DLG             161
#define IDD_FOGEFFECTS                  163
#define IDD_PARAMETRIC_TEXTURES         165
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_MATERIAL_AMBIENT            1039
#define IDC_MATERIAL_DIFFUSE            1040
#define IDC_TRANSLATION_SLIDER          1040
#define IDC_MATERIAL_SHININESS          1041
#define IDC_ROTATION_SLIDER             1041
#define IDC_MATERIAL_SPECULAR           1042
#define IDC_SCALING_SLIDER              1042
#define IDC_EDIT1                       1063
#define IDC_PERS_D_PARAM                1063
#define IDC_SUBOBJECT_NUMBER            1063
#define IDC_WIDTH_CONTROL               1063
#define IDC_RICHEDIT21                  1064
#define IDC_PERS_ALPHA_PARAM            1064
#define IDC_HEIGHT_CONTROL              1064
#define IDC_FOG_END_Y                   1064
#define IDC_FINENESSVALUE               1070
#define IDC_SUBCHECK                    1076
#define IDC_INVERT_VERTEX_NORMALS       1078
#define IDC_INVERT_POLYGON_NORMALS      1079
#define IDC_IMPORT_NORMALS              1080
#define IDC_CALCULATE_NORMALS           1081
#define IDC_IMPORTNORMALS               1081
#define IDC_SAVEAS                      1082
#define IDC_FilterSize                  1083
#define IDC_filter3                     1084
#define IDC_SIZE_3                      1084
#define IDC_filter5                     1085
#define IDC_boxFilter                   1086
#define IDC_BOX_FILTER                  1086
#define IDC_triangleFilter              1087
#define IDC_TRIANGE_FILTER              1087
#define IDC_gaussianFilter              1088
#define IDC_GAUSSIAN_FILTER             1088
#define IDC_sincFilter                  1089
#define IDC_SINC_FILTER                 1089
#define IDC_CHECK1                      1090
#define IDC_FOG_COLOR                   1091
#define IDC_FOG_BEGIN_Y                 1092
#define IDC_ENABLE_FOG                  1093
#define IDC_MODEL_NUMBER                1094
#define IDC_BUTTON1                     1097
#define IDC_MODULE_NUMBER               1098
#define IDC_ENABLE_TEXTURES             1099
#define IDC_NO_SIZE                     1100
#define IDC_SIZE_5                      1102
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_OPTIONS_MOUSESENSITIVITY     32799
#define ID_POLYNORMALS                  32802
#define ID_VERTIXNORMALS                32803
#define ID_VIEWSPACE                    32804
#define ID_OBJECTSPACE                  32805
#define ID_LINECOLORS                   32806
#define ID_BOXFRAME                     32807
#define ID_BACKGROUNDCOLOR              32810
#define ID_VERTEXNORMALS                32811
#define ID_LINECOLOR                    32812
#define ID_ACTION_VIEW                  32813
#define ID_ACTION_OBJECT                32814
#define ID_VIEW_BOUNDINGBOX             32815
#define ID_VIEW_POLYGONNORMALS          32816
#define ID_VIEW_VERTEXNORMALS           32817
#define ID_BOUNDINGBOX                  32818
#define ID_VIEW_OUTLINECOLOR            32819
#define ID_VIEW_BACKGROUNDCOLOR         32820
#define ID_VIEW_NORMALSCOLOR            32821
#define ID_NORMALSCOLOR                 32822
#define ID_OPTIONS_SETSENSITIVITYVARIABLES 32823
#define ID_OPTIONS_FINENESSCONTROL      32824
#define ID_NORMALCOLOR                  32828
#define ID_VIEW_SPLITSCREEN             32829
#define ID_VIEW_RESETVIEW               32830
#define ID_VIEW_OBJECTSELECTION         32831
#define ID_VIEW_BACKFACECULLING         32832
#define ID_FILE_LOADBACKGROUND          32833
#define ID_FILE_LOAD_OBJECT             32834
#define ID_VIEW_SILHOUETTE              32835
#define ID_OPTIONS_S                    32836
#define ID_SILHOUETTE_COLOR             32837
#define ID_SILHOUETTECOLOR              32838
#define ID_BACKGROUND_STRECHMODE        32841
#define ID_BACKGROUND_REPEATMODE        32842
#define ID_SOLIDRENDERING_TOSCREEN      32843
#define ID_SOLIDRENDERING_TOFILE        32844
#define ID_SHADING_PHONG                32845
#define ID_LIGHT_SHADING_PHONG          32846
#define ID_LIGHT_MATERIAL               32847
#define ID_SOLIDRENDERING_WIREFRAME     32848
#define ID_SOLIDRENDERING_WIREFRAMTOFILE 32849
#define ID_AXIS_XY                      32850
#define ID_AXIS_XY32851                 32851
#define ID_PLANE_XY                     32852
#define ID_SOLIDRENDERING_SUPERSAMPLINGANTI 32853
#define ID_VIEW_MOTIONBLUR              32854
#define ID_SHADING_LIGHT                32857
#define ID_FOG_PARAMETERS               32858
#define ID_TEXTURES_LOADTEXTURE         32859
#define ID_FOG_DISPLAYSCENEDEPTH        32860

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32861
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
